### ISSUE TITLE
TRIVIAL- Elección de preguntas

### ISSUE THREAD

**Issue by Zoraida-AP** [irenealonso11/juego_python#14]

**Comment by irenealonso11** [comment]
**TEMA: ENTRETENIMIENTO**
1. ¿Qué agente de la T.I.A. con gafas y que siempre va de traje tiene una gran capacidad para disfrazarse?
Mortadelo
2. ¿Cuál es la fruta favorita de los minions?
Los plátanos
3. ¿Cuál es el apellido de Rocky en la saga de películas del mismo título?
Balboa
4.  ¿Qué familia vive en la ciudad de Springfield?
Los Simpson
5. ¿Qué personaje de ficción fue creado por Elvira Lindo?
Manolito Gafotas
6. ¿Cómo se llama el perro de Tintín: ¿Milú, Pluto o Totó?  
Milú
7. ¿Cómo se llama la cabra que acompaña a Heidi?
Copito de nieve
8. ¿Cómo se llama a las personas que no poseen magia en la saga de Harry Potter?
Muggles
