### ISSUE TITLE
AHORCADO-Planteamiento NO CODE 

### ISSUE THREAD

**Issue by Zoraida-AP** [irenealonso11/juego_python#2]
Planteamiento del juego sin código.

**Comment by irenealonso11** [comment]
- La maquina elije una palabra de una lista de palabras. (random)
- Numero de intentos es limitado. (intentos +=1)
- Contador de aciertos.(Igual que la longitud de la palabra o numero de letras.)
- **BUCLE:**
- El jugador debe indicar una letra. (input)
- Si el jugador acierta:
          - una letra se coloca en el lugar correspondiente.
          - va a salir un mensaje de has acertado.
          - suma un acierto al contador.
          - contador aciertos = a numero de letras, se lanza mensaje de ganador.
          - meter break para parar el bucle..
- Si la letra del jugador esta en la palabra se mostrara la letra en la posición correspondiente.
- Si la letra no esta en la palabra:
        -  va a restar un intento.
        - añade una parte del cuerpo del ahorcado.
        - va a salir un mensaje de inténtalo otra vez.
- Esto se va repetir hasta que el jugador acierte la palabra o el limite de intentos sea 0.
- Si acierta se muestra mensaje de ha ganado.
- Si no acierta se muestra que ha perdido.
-
